apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-ha-pitr
  namespace: database
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:16.4

  storage:
    size: 5Gi

  backup:
    barmanObjectStore:
      destinationPath: s3://k8s-kops-kalyan
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip

